import {test,expect,chromium} from '@playwright/test';
import {mkdtemp,readdir,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {X509Certificate} from 'node:crypto';
import {unzipSync} from 'fflate';
import {WARCParser} from 'warcio';

test('canonical metadata templates render actual Sweeting WACZ offline',async({},info)=>{
  test.setTimeout(180000);
  const directory=process.env.ABX_LIVE_CAPTURE_DIR || '/var/folders/bk/63jsns1s0gvgtj8tdcss8vy80000gq/T/abx-wacz-acceptance-0lb8q1/captures';
  const files=await readdir(directory,{recursive:true});const file=files.find(file=>path.basename(file)==='sweeting-blog.wacz');if(!file)throw Error('Real sweeting-blog.wacz capture required');const archivePath=path.join(directory,file);
  const zip=unzipSync(await readFile(archivePath),{filter:file=>file.name.startsWith('archive/')});let dom='',ssl:any,ax:any;
  for(const bytes of Object.values(zip))for await(const record of new WARCParser([bytes])){const body=await record.readFully();const target=record.warcTargetURI || '';if(target.startsWith('urn:dom:'))dom=new TextDecoder().decode(body);if(target.startsWith('urn:sslcerts:'))ssl=JSON.parse(new TextDecoder().decode(body));if(target.startsWith('urn:accessibility:'))ax=JSON.parse(new TextDecoder().decode(body));}
  expect(dom).toContain('Sweeting');expect(ssl.connections.length).toBeGreaterThan(0);expect(ax.nodes.length).toBeGreaterThan(10);
  const axByID=new Map<string,any>();for(const node of ax.nodes){if(axByID.has(node.nodeId))expect(node).toEqual(axByID.get(node.nodeId));axByID.set(node.nodeId,node);}const axRoot=ax.nodes.find((node:any)=>!node.parentId||!axByID.has(node.parentId));const reachable=new Set<string>();const visit=(id:string)=>{expect(axByID.has(id)).toBe(true);if(reachable.has(id))return;reachable.add(id);for(const child of axByID.get(id)?.childIds || [])visit(child);};visit(axRoot.nodeId);expect(reachable.size).toBe(axByID.size);const expectedAXNodes=reachable.size;
  const extension=path.resolve('.output/chrome-mv3');const context=await chromium.launchPersistentContext(await mkdtemp(path.join(tmpdir(),'abx-metadata-templates-')),{channel:'chromium',headless:true,acceptDownloads:true,viewport:{width:1400,height:1000},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
  const live:string[]=[],errors:string[]=[];
  try{const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const studio=await context.newPage();studio.on('pageerror',error=>errors.push(String(error)));await studio.goto(`chrome-extension://${new URL(worker.url()).host}/studio.html`);await context.grantPermissions(['clipboard-read','clipboard-write']);await context.setOffline(true);context.on('request',request=>{if(/^https?:/.test(request.url()))live.push(request.url());});
    const expected=await studio.evaluate(source=>{const doc=new DOMParser().parseFromString(source,'text/html');return {title:doc.querySelector('meta[property="og:title"]')?.getAttribute('content')||doc.title,description:doc.querySelector('meta[property="og:description"]')?.getAttribute('content')||doc.querySelector('meta[name="description"]')?.getAttribute('content')||''};},dom);
    const choosing=studio.waitForEvent('filechooser');await studio.getByRole('button',{name:'Import WACZ',exact:true}).click();await(await choosing).setFiles(archivePath);await expect(studio.locator('.snapshot-detail')).toBeVisible({timeout:60000});
    async function open(plugin:string,title:string){await studio.goto(studio.url().split('#')[0]+'#view='+plugin);const host=studio.locator('#main-frame-wrapper .plugin-view');await expect(host).toHaveAttribute('data-plugin',plugin);const frame=host.frameLocator(`iframe[title="${title}"]`);await expect(frame.locator('header h1')).toContainText(title);return {host,frame};}
    let {host,frame}=await open('seo','SEO');await expect(frame.locator('.social .link-copy h2')).toHaveText(expected.title);if(expected.description)await expect(frame.locator('.link-copy p')).toHaveText(expected.description);
    for(const label of ['Like','Comment','Share'])await expect(frame.getByRole('img',{name:label,exact:true})).toBeVisible();await expect(frame.locator('details.metadata')).toHaveAttribute('open','');
    await expect.poll(()=>frame.locator('.link-preview > img').evaluateAll(images=>images.some(image=>(image as HTMLImageElement).naturalWidth>0&&(image as HTMLImageElement).currentSrc.includes('/w/')))).toBe(true);
    const seoHeight=await host.locator('iframe').evaluate((iframe:HTMLIFrameElement)=>({height:iframe.getBoundingClientRect().height,body:iframe.contentDocument!.body.scrollHeight}));expect(Math.abs(seoHeight.height-seoHeight.body)).toBeLessThan(50);await studio.screenshot({path:info.outputPath('canonical-seo.png')});
    ({host,frame}=await open('sslcerts','SSL Certificates'));await expect(frame.locator('.cert.leaf').first()).toBeVisible();await expect(frame.locator('.session').first()).toContainText(ssl.connections[0].securityDetails.protocol);
    const originalChain=ssl.certificates.find((item:any)=>item.origin===new URL(ssl.connections[0].url).origin).tableNames;expect(originalChain.length).toBeGreaterThan(1);const rootDER=Buffer.from(originalChain.at(-1),'base64');const certificate=new X509Certificate(rootDER);const fingerprint=certificate.fingerprint256.replaceAll(':','').toLowerCase();const card=frame.locator('.cert').first();await expect(card.locator('.hash-row code').last()).toHaveText(fingerprint);
    await card.locator('.hash-row').last().getByRole('button',{name:'Copy',exact:true}).click();await expect(card.getByRole('button',{name:'Copied',exact:true})).toBeVisible();expect(await studio.evaluate(()=>navigator.clipboard.readText())).toBe(fingerprint);
    const downloading=studio.waitForEvent('download');await card.getByRole('link',{name:'⤓ PEM',exact:true}).click();const pemPath=info.outputPath('certificate.pem');await(await downloading).saveAs(pemPath);const pem=await readFile(pemPath,'utf8');expect(Buffer.from(pem.replace(/-----[^-]+-----|\s/g,''),'base64').equals(rootDER)).toBe(true);await expect(card.getByRole('link',{name:'◫ CT logs',exact:true})).toHaveAttribute('href','https://ctlogs.dev/search?q='+fingerprint);await studio.screenshot({path:info.outputPath('canonical-ssl.png')});
    ({host,frame}=await open('accessibility','Accessibility'));await expect(frame.getByRole('heading',{name:'Page semantics',exact:true})).toBeVisible();await expect(frame.locator('.badges').first()).toContainText(`◇ ${expectedAXNodes} AX nodes`);await expect(frame.getByRole('heading',{name:'Document outline',exact:true})).toBeVisible();expect(await frame.locator('.outline-row').count()).toBeGreaterThan(10);
    const closed=frame.locator('.ax details:not([open]) > summary').filter({visible:true}).first();await expect(closed).toBeVisible();const summary=await closed.elementHandle();await summary!.click();await expect.poll(()=>summary!.evaluate(element=>element.parentElement!.hasAttribute('open'))).toBe(true);await studio.screenshot({path:info.outputPath('canonical-accessibility.png')});
    await frame.getByRole('link',{name:'View all files',exact:true}).click();await expect(studio.locator('#main-frame-wrapper .plugin-view')).toHaveAttribute('data-plugin','accessibility');await expect(studio.locator('.plugin-files').getByRole('link',{name:/^accessibility-.*\.json$/})).toBeVisible();
    const embeddedURL=await studio.locator('.thumb-card[data-plugin-name="seo"] a[title="Open output in a new tab"]').getAttribute('href');expect(embeddedURL).toBeTruthy();const embedded=await context.newPage();embedded.on('pageerror',error=>errors.push(String(error)));await embedded.goto(embeddedURL!);const embeddedSEO=embedded.frameLocator('iframe[title="SEO"]');await expect(embeddedSEO.locator('.link-copy h2')).toHaveText(expected.title);await embeddedSEO.getByRole('link',{name:'View all files',exact:true}).click();await expect(embedded.locator('.plugin-view')).toHaveAttribute('data-plugin','seo');await expect(embedded.locator('.plugin-files').getByRole('heading',{name:'SEO',exact:true})).toBeVisible();await embedded.close();
    expect(live,'No live HTTP requests from offline metadata templates').toEqual([]);expect(errors).toEqual([]);await expect(studio.getByRole('alert')).toHaveCount(0);
    await writeFile(info.outputPath('verification.json'),JSON.stringify({seoHeight,certificateFingerprint:fingerprint,AXNodes:expectedAXNodes,AXRecords:ax.nodes.length,live,errors},null,2));
  }finally{await context.close();}
});
