import { test, expect, chromium } from '@playwright/test';
import {mkdtemp,readdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';

test('real Sweeting WACZ uses ArchiveBox snapshot stacks, plugin cards and article readers offline',async({},testInfo)=>{
  test.setTimeout(180_000);
  const root=process.env.ABX_LIVE_CAPTURE_DIR!;
  const relative=(await readdir(root,{recursive:true})).find(file=>path.basename(file)==='sweeting-blog.wacz');
  expect(relative,'Retained real Sweeting blog capture').toBeTruthy();
  const extension=path.resolve('.output/chrome-mv3');
  const context=await chromium.launchPersistentContext(await mkdtemp(path.join(tmpdir(),'abx-snapshot-ui-')),{channel:'chromium',headless:true,viewport:{width:1440,height:1000},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
  try{
    const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');
    const page=await context.newPage();const errors:string[]=[];const live:string[]=[];
    page.on('pageerror',e=>errors.push(String(e)));context.on('request',request=>{if(/^https?:/.test(request.url()))live.push(request.url())});
    await page.goto(`chrome-extension://${new URL(worker.url()).host}/studio.html`);await context.setOffline(true);
    const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Import WACZ',exact:true}).click();await(await chooser).setFiles(path.join(root,relative!));
    await expect(page.locator('.stack-shelf')).toBeVisible({timeout:90_000});
    expect(await page.locator('.stack-heading strong').allTextContents()).toEqual(['HTML','Raster','Article text','Embedded media','Metadata','Other files']);
    await expect(page.getByRole('button',{name:'Document',exact:true})).toHaveCount(0);
    await expect(page.locator('.snapshot-detail>header')).toHaveCSS('background-color','rgb(170, 30, 85)');
    expect(await page.locator('.stack-cover').evaluateAll(covers=>covers.every(cover=>cover.getBoundingClientRect().width>150))).toBe(true);
    // Verify visible collapsed covers before any stack is expanded.
    await expect(page.locator('.header-top')).toHaveCSS('padding','6px 32px 6px 10px');
    await expect(page.locator('.header-bottom')).toHaveCSS('padding','6px 8px 7px');
    await expect(page.locator('.stack-tray')).toBeHidden();
    await expect(page.locator('.output-stack-html .stack-cover')).toContainText('WACZ');
    await expect.poll(()=>page.locator('.output-stack-raster .stack-cover img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);
    const cover=page.locator('.output-stack-article_text .stack-cover').frameLocator('iframe').frameLocator('iframe[title="readability view"]').frameLocator('iframe[title="Readability full view"]');
    await expect(cover.locator('header')).toBeHidden();
    await expect(cover.frameLocator('iframe[title="Readability reader view"]').locator('body')).toContainText('Sweeting');
    await expect.poll(()=>cover.frameLocator('iframe[title="Readability reader view"]').locator('img').evaluateAll(images=>images.filter(img=>(img as HTMLImageElement).naturalWidth>0).length)).toBeGreaterThan(0);
    const originals=page.locator('.output-stack-embedded_media .stack-cover [data-resource-preview="liteparse"] .liteparse-thumbnail');
    await expect(originals).toBeVisible();
    await expect.poll(()=>originals.locator('img').evaluateAll(images=>images.filter(img=>(img as HTMLImageElement).naturalWidth>0).length)).toBeGreaterThan(0);
    const semantics=page.locator('.output-stack-metadata .stack-cover').frameLocator('iframe').frameLocator('iframe[title="Accessibility view"]').frameLocator('iframe[title="Accessibility"]');
    await expect(semantics.getByRole('heading',{name:'Page semantics',exact:true})).toBeVisible();
    await expect(semantics.locator('header')).toBeHidden();
    const search=page.locator('.output-stack-other .stack-cover').frameLocator('iframe[title="Search archived text preview"]');
    await expect(search.getByRole('searchbox',{name:'Search archived text',exact:true})).toBeVisible();
    await expect(search.locator('.view-section .muted')).toHaveText(/[1-9]\d* archived documents ready to search/);
    await expect(page.getByRole('button',{name:'Toggle saved outputs'})).toHaveAttribute('aria-expanded','true');
    await page.getByRole('button',{name:'Toggle saved outputs'}).click();
    await expect(page.locator('.header-bottom')).toBeHidden();
    await page.getByRole('button',{name:'Toggle saved outputs'}).click();
    await expect(page.locator('.header-bottom')).toBeVisible();
    await page.screenshot({path:testInfo.outputPath('archivebox-collapsed-stack-previews.png')});
    await page.locator('.output-stack-other').click();
    await expect(page.locator('.stack-tray')).toHaveAttribute('aria-label','Other files');
    const savedFiles=page.locator('.stack-tray .loose-items a');await expect(savedFiles.first()).toBeVisible();
    for(const link of await savedFiles.all())await expect(link).toHaveAttribute('href',/^#view=\w+&files=1$/);
    await page.locator('.output-stack-article_text').click();
    await expect(page.locator('.stack-tray')).toHaveAttribute('aria-label','Article text');
    expect(await page.locator('.stack-tray .thumb-card').evaluateAll(cards=>cards.map(card=>(card as HTMLElement).dataset.pluginName))).toEqual(['readability','defuddle','mercury','htmltotext']);
    await expect(page.locator('.stack-tray .abx-output-icon--readability')).toBeVisible();
    const card=page.locator('.stack-tray .thumb-card[data-plugin-name="readability"]');
    await card.locator('.thumbnail-click-overlay').click();
    await expect(page.locator('#main-frame-wrapper .plugin-view')).toHaveAttribute('data-plugin','readability');
    const shell=page.locator('#main-frame-wrapper').frameLocator('iframe[title="Readability full view"]');
    const reader=shell.frameLocator('iframe[title="Readability reader view"]');
    await expect(reader.locator('body')).toContainText('Sweeting');
    await expect.poll(()=>reader.locator('img').evaluateAll(images=>images.filter(img=>(img as HTMLImageElement).naturalWidth>0).length),{timeout:30_000}).toBeGreaterThan(0);
    await expect(card.frameLocator('iframe').frameLocator('iframe[title="readability view"]').frameLocator('iframe[title="Readability full view"]').locator('header')).toBeHidden();
    await page.screenshot({path:testInfo.outputPath('archivebox-article-stacks.png'),fullPage:true});
    await page.locator('.output-stack-metadata').click();
    await expect(page.locator('.stack-tray .thumb-card[data-plugin-name="seo"]')).toBeVisible();
    await page.locator('.stack-tray .thumb-card[data-plugin-name="seo"] .thumbnail-click-overlay').click();
    await expect(page.locator('#main-frame-wrapper .plugin-view')).toHaveAttribute('data-plugin','seo');
    await page.screenshot({path:testInfo.outputPath('archivebox-metadata-stacks.png'),fullPage:true});
    await writeFile(testInfo.outputPath('browser-errors.json'),JSON.stringify({errors,live},null,2));
    expect(errors).toEqual([]);expect(live,'Offline views must only use WACZ data').toEqual([]);
  }finally{await context.close()}
});
